from .constantes import NUM_AGENCIA, CONTASCORRENTS_DIR, USUARIOS_DIR, MSG_SALDO_INSUF, MSG_SALDO_LIMITE, MSG_SALDO_LIMITE_DIARIO, LIMITE, LIMITE_SAQUES, LIMITE_TRANSFERENCIA
from .jsonFuncs import carregarJSON, escreverJSON
